config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: { registrations: 'registrations' }
    resources :interviews
    resources :questions
    resources :question_categories
    resources :students
    resources :interview_questions

    root to: 'students#index'

    scope '/admin' do
        resources :users
    end

end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
    before_action :set_interview, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
    load_and_authorize_resource

    # GET /interviews
    # GET /interviews.json
    def index
        @interviews = current_user.roles.first.name == "admin" ? Interview.all  :  Interview.where("interviewer_id =? ", current_user.id)
    end

    # GET /interviews/1
    # GET /interviews/1.json
    def show; end

    # GET /interviews/new
    def new
        @interview = Interview.new
    end

    # GET /interviews/1/edit
    def edit; end

    # POST /interviews
    # POST /interviews.json
    def create
        @interview = Interview.new(interview_params)

        respond_to do |format|
            if @interview.save
                format.html { redirect_to @interview, notice: 'Interview was successfully created.' }
                format.json { render :show, status: :created, location: @interview }
            else
                format.html { render :new }
                format.json { render json: @interview.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /interviews/1
    # PATCH/PUT /interviews/1.json
    def update
        respond_to do |format|
            if @interview.update(interview_params)
                format.html { redirect_to @interview, notice: 'Interview was successfully updated.' }
                format.json { render :show, status: :ok, location: @interview }
            else
                format.html { render :edit }
                format.json { render json: @interview.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /interviews/1
    # DELETE /interviews/1.json
    def destroy
        @interview.destroy
        respond_to do |format|
            format.html { redirect_to interviews_url, notice: 'Interview was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_interview
        @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
        params.require(:interview).permit(:start_slot, :end_slot, :kind, :description, :remarks, :student_id, :user_id, :interviewer_id, :level, :marks, question_category_ids: [])
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.erb
<%= form_for(@interview) do |f| %>
<% if @interview.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@interview.errors.count, "error") %>
        prohibited this interview from being saved:</h2>
    <ul>
        <% @interview.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= f.label :start_time %><br>
    <br/>
    <%= f.datetime_select :start_slot %>
</div><br>
<div class="field">
    <%= f.label :end_time %><br>
    <br/>
    <%= f.datetime_select :end_slot %>
</div><br>
<div class="field">
    <%= f.label :interview_type %><br>
    <%= f.radio_button :kind, "Online" %>On-line
    <%= f.radio_button :kind, "Offline" %>Off-line
</div><br>
<div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
</div><br>

<div class="field">
    <%= f.label :student_id %><br>
    <%= f.collection_select :student_id, Student.all, :id, :name, prompt: "Select Student" %>
</div><br>
<div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
</div><br>
<div class="field">
    <%= f.label :Select_the_interviewer %><br>
    <%= f.collection_select :interviewer_id, User.all, :id, :email, prompt: "Select an Interviewer" %>
</div><br>
<div class="field">
    <%= f.label :question_category %>
    <br>
    <%= f.collection_check_boxes :question_category_ids, QuestionCategory.all, :id, :name do |b| %>
    <%= b.check_box %>
    <%= b.label %>
    <% end %>
</div><br>

<div class="field">
    <%= f.label :Select_level_of_Interview %><br>
    <%= f.radio_button :level, "easy"%>Easy
    <%= f.radio_button :level, "medium"%>Medium
    <%= f.radio_button :level, "hard"%>Hard
</div>

<div class="actions">
    <%= f.submit %>
</div>
<% end %>

app/views/interviews/edit.html.erb
<h1>Editing Interview</h1>

<%= render 'form' %>

<%= link_to 'Show', @interview %> |
<%= link_to 'Back', interviews_path %>

app/views/interviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Interviews</h1>

<table>
    <thead>
        <tr>
            <th>Start Slot</th>
            <th>End Slot</th>
            <th>Type</th>
            <th>Description</th>
            <th>Remarks</th>
            <th>Student</th>
            <th>Marks</th>
            <th>Interviewer</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @interviews.each do |interview| %>
        <tr>
            <td><%= interview.start_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
            <td><%= interview.end_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
            <td><%= interview.kind %></td>
            <td><%= interview.description %></td>
            <td><%= interview.remarks %></td>
            <td><%= interview.student.try(:name) %></td>
            <td><%= interview.marks %></td>
            <td><%= interview.interviewer.try(:username) %></td>
            <td><%= link_to 'Show', interview %></td>
            <% if current_user.role? "admin" %>
            <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
            <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
        </tr>
        <% end %>
    </tbody>
</table>
</br>
<%= link_to 'New Interview', new_interview_path %>
<% if current_user.role? "admin" %>
<script>
$(function () {
    $("#accordion").accordion({collapsible: true});
});
</script>
<div id="accordion">
<h3>
    <em>
        Stats Of Interviews
    </em>
</h3>
<div>
    <b>
        <u>
            Completed Interviews:-
            <%= Interview.where('start_slot < ? AND end_slot < ?', DateTime.now, DateTime.now ).count %>
        </u>
    </b>
    <table>
        <thead>
            <tr>
                <th>Start Slot</th>
                <th>End Slot</th>
                <th>Type</th>
                <th>Description</th>
                <th>Remarks</th>
                <th>Student</th>
                <th>Marks</th>
                <th>Interviewer</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% Interview.where('start_slot < ? AND end_slot < ?', DateTime.now, DateTime.now).each do |interview| %>
            <tr>
                <td><%= interview.start_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.end_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.kind %></td>
                <td><%= interview.description %></td>
                <td><%= interview.remarks %></td>
                <td><%= interview.student.try(:name) %></td>
                <td><%= interview.marks %></td>
                <td><%= interview.interviewer.try(:username) %></td>
                <td><%= link_to 'Show', interview %></td>
                <% if current_user.role? "admin" %>
                <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
                <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
    <b>
        <u>
            Upcoming Interviews:-
            <%= Interview.where('start_slot > ? AND end_slot > ?', DateTime.now, DateTime.now ).count %>
        </u>
    </b>
    <table>
        <thead>
            <tr>
                <th>Start Slot</th>
                <th>End Slot</th>
                <th>Type</th>
                <th>Description</th>
                <th>Remarks</th>
                <th>Student</th>
                <th>Marks</th>
                <th>Interviewer</th>
                <th colspan="3"></th>
            </tr>
        </thead>
        <tbody>
            <% Interview.where('start_slot > ?', DateTime.now ).each do |interview| %>
            <tr>
                <td><%= interview.start_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.end_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.kind %></td>
                <td><%= interview.description %></td>
                <td><%= interview.remarks %></td>
                <td><%= interview.student.try(:name) %></td>
                <td><%= interview.marks %></td>
                <td><%= interview.interviewer.try(:username) %></td>
                <td><%= link_to 'Show', interview %></td>
                <% if current_user.role? "admin" %>
                <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
                <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>

    <b>
        <u>
            On-Going Interviews:-
            <%= Interview.where('start_slot <= ? AND end_slot >= ?',  DateTime.now, DateTime.now ).count %>
        </u>
    </b>

    <table>
        <thead>
            <tr>
                <th>Start slot</th>
                <th>End slot</th>
                <th>Type</th>
                <th>Description</th>
                <th>Remarks</th>
                <th>Student</th>
                <th>Marks</th>
                <th>Interviewer</th>
                <th colspan="3"></th>
            </tr>
        </thead>

        <tbody>
            <% Interview.where('start_slot <= ? AND end_slot >= ?',  DateTime.now, DateTime.now ).each do |interview| %>
            <tr>
                <td><%= interview.start_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.end_slot.strftime("%B %e, %Y at %I:%M %p") %></td>
                <td><%= interview.kind %></td>
                <td><%= interview.description %></td>
                <td><%= interview.remarks %></td>
                <td><%= interview.student.try(:name) %></td>
                <td><%= interview.marks %></td>
                <td><%= interview.interviewer.try(:username) %></td>
                <td><%= link_to 'Show', interview %></td>
                <% if current_user.role? "admin" %>
                <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
                <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                <% end %>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>
</div>

<% end %>
</br>
</br>

<script>
$(document).ready(function () {
    $('#calendar').fullCalendar({
        defaultDate: '<%= Date.today.strftime("%Y-%m-%d") %>', eventLimit: true, // allow "more" link when too many events
        events: [
            <% Interview.where('start_slot > ?', DateTime.now ).each do |interview| %>
            {
                title: "<%= interview.student.try(:name) %>",
                start: '<%= interview.start_slot.strftime("%Y-%m-%d") %>',
                end: '<%= interview.end_slot %>'
            },
            <% end %>
        ]
    });
});
</script>

<div id="calendar"></div>

app/views/interviews/new.html.erb
<h1>New Interview</h1>

<%= render 'form' %>

<%= link_to 'Back', interviews_path %>

app/views/interviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Start Slot:</strong>
    <%= @interview.start_slot.strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
    <strong>End Slot:</strong>
    <%= @interview.end_slot.strftime("%B %e, %Y at %I:%M %p") %>
</p>

<p>
    <strong>Type:</strong>
    <%= @interview.kind %>
</p>

<p>
    <strong>Description:</strong>
    <%= @interview.description %>
</p>

<p>
    <strong>Student:</strong>
    <%= @interview.student.try(:name) %>
</p>

<p>
    <strong>User:</strong>
    <%= @interview.user_id %>
</p>

<p>
    <strong>Interviewer:</strong>
    <%= @interview.interviewer.try(:username) %>
</p>

<p>
    <strong>
        Interview_On:
    </strong>
    <%= @interview.question_category_ids %>
</p>

<% sum = 0
  if i = @interview.interview_questions.where('responce = ?', "satisfied").count
      sum+=i
  end
  if j = @interview.interview_questions.where('responce = ?', "not-satisfied").count
      j = j/2.to_f
      sum+=j
  end
%>
<p>
    <strong>
        Marks:-
    </strong>
    <b>
        <em>
            <% @interview.update(marks:sum.to_f)%>
            <%= @interview.marks %>/<%= @interview.interview_questions.count %>
        </em>
    </b>
</p>
<table>
    <thead>
        <tr>
            <th>Satisfied</th>
            <th>Not Satisfied</th>
            <th>Not Answered</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @interview.interview_questions.where('responce = ?', "satisfied").count %></td>
            <td><%= @interview.interview_questions.where('responce = ?', "not-satisfied").count %></td>
            <td><%= @interview.interview_questions.where('responce = ?', "not-answered").count %></td>
        </tr>
    </tbody>
</table>

<p>
    <strong>Remarks:</strong>
    <%= @interview.remarks %>
</p>

<h3>
    Interview Questions</h3>
<% @interview.interview_questions.all.each do |interview_question| %>
<ul>
    <li>
        <%= form_for interview_question do |f| %>
        <%= interview_question.question.try(:title)%>
        <%= f.radio_button :responce, "satisfied" %>
        Satisfied
        <%= f.radio_button :responce, "not-satisfied"  %>
        Not Satisfied
        <%= f.radio_button :responce, "not-answered" %>
        Not Answered
        <% if interview_question.responce.nil? %>
        <%= f.submit %>
        <% end %>
        <% end %>
    </li>
</ul>
<% end %>
<% if @interview.remarks.nil? %>
<%= form_for(@interview) do |f| %>
<div class="field">
    <%= f.label :remarks %><br>
    <%= f.text_area :remarks %><br>

    <%= f.submit %>
</div>
<% end %>
<% end %>

<%= link_to 'Edit', edit_interview_path(@interview) %>
|
<%= link_to 'Back', interviews_path %>