config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: { registrations: 'registrations' }
    resources :interviews
    resources :questions
    resources :question_categories
    resources :students
    resources :interview_questions

    root to: 'students#index'

    scope '/admin' do
        resources :users
    end

end

app/models/question_category.rb
class QuestionCategory < ActiveRecord::Base
    has_many :questions

    has_many :interview_question_categories
    has_many :interviews, through: :interview_question_categories
end

app/controllers/question_categories_controller.rb
class QuestionCategoriesController < ApplicationController
    before_action :set_question_category, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
    load_and_authorize_resource

    # GET /question_categories
    # GET /question_categories.json
    def index
        @question_categories = QuestionCategory.all
    end

    # GET /question_categories/1
    # GET /question_categories/1.json
    def show; end

    # GET /question_categories/new
    def new
        @question_category = QuestionCategory.new
    end

    # GET /question_categories/1/edit
    def edit; end

    # POST /question_categories
    # POST /question_categories.json
    def create
        @question_category = QuestionCategory.new(question_category_params)

        respond_to do |format|
            if @question_category.save
                format.html { redirect_to @question_category, notice: 'Question category was successfully created.' }
                format.json { render :show, status: :created, location: @question_category }
            else
                format.html { render :new }
                format.json { render json: @question_category.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /question_categories/1
    # PATCH/PUT /question_categories/1.json
    def update
        respond_to do |format|
            if @question_category.update(question_category_params)
                format.html { redirect_to @question_category, notice: 'Question category was successfully updated.' }
                format.json { render :show, status: :ok, location: @question_category }
            else
                format.html { render :edit }
                format.json { render json: @question_category.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /question_categories/1
    # DELETE /question_categories/1.json
    def destroy
        @question_category.destroy
        respond_to do |format|
            format.html { redirect_to question_categories_url, notice: 'Question category was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_question_category
        @question_category = QuestionCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_category_params
        params.require(:question_category).permit(:name)
    end
end

app/helpers/question_categories_helper.rb
module QuestionCategoriesHelper
end

app/views/question_categories/_form.html.erb
<%= form_for(@question_category) do |f| %>
  <% if @question_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question_category.errors.count, "error") %> prohibited this question_category from being saved:</h2>

      <ul>
      <% @question_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/question_categories/edit.html.erb
<h1>Editing Question Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @question_category %> |
<%= link_to 'Back', question_categories_path %>

app/views/question_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Question Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @question_categories.each do |question_category| %>
      <tr>
        <td><%= question_category.name %></td>
        <td><%= link_to 'Show', question_category %></td>
        <td><%= link_to 'Edit', edit_question_category_path(question_category) %></td>
        <td><%= link_to 'Destroy', question_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question category', new_question_category_path %>

app/views/question_categories/new.html.erb
<h1>New Question Category</h1>

<%= render 'form' %>

<%= link_to 'Back', question_categories_path %>

app/views/question_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @question_category.name %>
</p>

<%= link_to 'Edit', edit_question_category_path(@question_category) %> |
<%= link_to 'Back', question_categories_path %>